apiVersion: v1
kind: Service
metadata:
  name: gateway-webapps
spec:
  ports:
    - name: "8080-tcp"
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: gateway-webapps
  type: LoadBalancer
  loadBalancerIP: 35.224.158.140